#' plot the recruitment model in two panels a) R~f(S) and b) R~f(Year)
#'
#' @import futR
#' @email For more information contact author Kirstin Holsman (kirstin.holsman@noaa.gov)
#' @weblink 
#' @param rec_df    dataframe of recruitment and spawners generated by getFit()
#' @param cbp       color_brewer palette for the different models; default = "Dark2"
#' @param obscol    color for the "observed" recruitment; default = "gray"
#' @return list
#'
#' @examples
#' # read in the data
#' datlist <- datlist2 <-  readMake_futR_data("data/in/futR_Inputs.xlsx" )
#' mm      <- runmod(dlistIN   = datlist, version   = 'futR',recompile = FALSE,simulate  = TRUE,sim_nitr  = 1000)
#' r_fit  <- getFit(mm, nm = paste0("recType = ",datlist$rs_dat$rectype))
#' plot_rs(r_fit)
#' 
#' # set the recType to 2
#' datlist2$rs_dat$rectype <- 2
#' mm      <- runmod(dlistIN   = datlist2, version   = 'futR',recompile = FALSE,simulate  = TRUE,sim_nitr  = 1000)
#' r_fit2  <- getFit(mm, nm = paste0("recType = ",datlist2$rs_dat$rectype))
#' 
#' # now compare plots
#' plot_rs(rbind(r_fit,r_fit2))
#' @export
plot_rs <- function(rec_df = rec_fit, cbp = "Dark2", obscol = "gray"){
  Rmax <- 1.05* max( max(rec_df$R_obs), max(rec_df$R_hat))
  Smax <- 1.05* max( max(rec_df$S_obs), max(rec_df$S_hat))
  
  prs <- ggplot(data =  rec_df) +
    geom_point (aes(x=S_obs,y = R_obs),color=obscol,size =2)+ 
    xlab("Spawner Index")+
    ylab("Recruitment")+    
    coord_cartesian(ylim = c(0, Rmax),xlim = c(0, Smax))+
    geom_point (aes(x=S_obs,y = R_hat, color = model))+ 
    theme_minimal()
  
  prt <- ggplot(data =  rec_df) +
    geom_point (aes(x=year,y = R_obs),color=obscol,size =2)+ 
    coord_cartesian(ylim = c(0, Rmax))+
    xlab("Year")+
    ylab("Recruitment")+    
    geom_point (aes(x=year,y = R_hat, color = model))+ 
    geom_line (aes(x=year,y = R_hat, color = model))+ 
    theme_minimal()
  #display.brewer.all()
  #col(1)
  library("cowplot")
  plot_grid(prs, prt, #bp + rremove("x.text"), 
            labels = c("A", "B"),
            ncol = 1, nrow = 2)
  
  
}