#' plot_rs
#' 
#' plot the recruitment model in two panels a) R~f(S) and b) R~f(Year)
#' For more information contact author Kirstin Holsman (kirstin.holsman at noaa.gov)
#'  
#' @import futR
#'  
#' @param rec_df dataframe of recruitment and spawners generated by getFit(), column headers include
#' * R_obs (recruitment)
#' * S_obs (Spawning biomass)
#' * R_hat (fitted Recruitment)
#' * S_hat (predicted spawning biomass )
#' * year (recruitment year)
#' * model (factor of rec model names)
#' @param cbp color_brewer palette for the different models; default = "Dark2"
#' @param obscol color for the "observed" recruitment; default = "gray"
#' @return list
#'
#' @examples
#' # add
#' @export
#' 
plot_rs <- function(rec_df, cbp = "Dark2", obscol = "gray"){
  require("cowplot")
  require("ggplot2")
  
  Rmax <- 1.05* max( max(rec_df$R_obs), max(rec_df$R_hat))
  Smax <- 1.05* max( max(rec_df$S_obs), max(rec_df$S_hat))
  
  prs <- ggplot2::ggplot(data =  rec_df) +
    ggplot2::geom_point(aes(x=S_obs,y = R_obs),color=obscol,size =2)+ 
    ggplot2::xlab("Spawner Index")+
    ggplot2::ylab("Recruitment")+    
    ggplot2::coord_cartesian(ylim = c(0, Rmax),xlim = c(0, Smax))+
    ggplot2::geom_point (aes(x=S_obs,y = R_hat, color = model))+ 
    ggplot2::theme_minimal()
  
  prt <- ggplot2::ggplot(data =  rec_df) +
    ggplot2::geom_point(aes(x=year,y = R_obs),color=obscol,size =2)+ 
    ggplot2::coord_cartesian(ylim = c(0, Rmax))+
    ggplot2::xlab("Year")+
    ggplot2::ylab("Recruitment")+    
    ggplot2::geom_point (aes(x=year,y = R_hat, color = model))+ 
    ggplot2::geom_line (aes(x=year,y = R_hat, color = model))+ 
    ggplot2::theme_minimal()
  #display.brewer.all()
  #col(1)
  cowplot::plot_grid(prs, prt, #bp + rremove("x.text"), 
            labels = c("A", "B"),
            ncol = 1, nrow = 2)
  
  
}